branches:
  only:
    - master

sudo: required

language: java

jdk:
  - openjdk11

services:
  - docker

before_install:
  - echo "artifactory_contextUrl=${AR_URL}" >> $HOME/.gradle/gradle.properties

after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - ./gradlew clean build
  - docker build -t resnyx .
  - docker tag resnyx:latest 902382300595.dkr.ecr.us-east-1.amazonaws.com/resnyx:latest
  - eval $(aws ecr get-login --region us-east-1 --no-include-email)
  - docker push 902382300595.dkr.ecr.us-east-1.amazonaws.com/resnyx:latest

notifications:
  webhooks:
    urls:
      - https://resnyx.sergeybochkov.com/travis